const mongoose = require("mongoose");

const playlistSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
  },
  imageURL: {
    type: String,
  },
  songs: [{ type: mongoose.Schema.ObjectId, ref: "song" }],
  creator: {
    type: mongoose.Schema.ObjectId,
    ref: "user",
  },
  section: {
    type: mongoose.Schema.ObjectId,
    ref: "section",
  },
  // True when the playlist is created by server itself
  isAutoGenerated: {
    type: Boolean,
    default: false,
  },
});

playlistSchema.pre(/^find/, function (next) {
  this.populate({ path: "songs creator section" });
});

const Playlist = mongoose.model("playlist", playlistSchema);

module.exports = Playlist;
